#!/usr/bin/env bash
set -Eeuo pipefail

PROGRAM_NAME="${0##*/}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ACTION="install"
ROLE="all"
FORCE=0
PURGE=0

INSTALL_BASE="/usr/local/lib/harbor-relay"
RELEASES_DIR="${INSTALL_BASE}/releases"
README_TARGET="${INSTALL_BASE}/README.md"
MANIFEST_TARGET="${INSTALL_BASE}/manifest.txt"

BIN_DIR="/usr/local/bin"
RELAY_BIN_LINK="${BIN_DIR}/harbor-relay"
AGENT_BIN_LINK="${BIN_DIR}/harbor-relay-agent"

CONFIG_DIR="/etc/harbor-relay"
EXAMPLES_DIR="${CONFIG_DIR}/examples"
RELAY_CONFIG="${CONFIG_DIR}/relay.yaml"
AGENT_CONFIG="${CONFIG_DIR}/agent.yaml"

RELAY_WORKDIR="/var/lib/harbor-relay"
AGENT_WORKDIR="/var/lib/harbor-relay-agent"
AGENT_DOCKER_CONFIG_DIR="${AGENT_WORKDIR}/docker-config"

SYSTEMD_DIR="/etc/systemd/system"
RELAY_SERVICE_NAME="harbor-relay"
AGENT_SERVICE_NAME="harbor-relay-agent"
RELAY_SERVICE_FILE="${SYSTEMD_DIR}/${RELAY_SERVICE_NAME}.service"
AGENT_SERVICE_FILE="${SYSTEMD_DIR}/${AGENT_SERVICE_NAME}.service"

TMP_DIR=""
PAYLOAD_ROOT=""
PAYLOAD_README=""
PAYLOAD_MANIFEST=""
PAYLOAD_RELAY_BIN=""
PAYLOAD_AGENT_BIN=""
PAYLOAD_RELAY_CONFIG=""
PAYLOAD_AGENT_CONFIG=""
PAYLOAD_RELAY_SERVICE=""
PAYLOAD_AGENT_SERVICE=""

log() {
    printf '[INFO] %s\n' "$*"
}

warn() {
    printf '[WARN] %s\n' "$*" >&2
}

die() {
    printf '[ERROR] %s\n' "$*" >&2
    exit 1
}

cleanup() {
    if [[ -n "${TMP_DIR}" && -d "${TMP_DIR}" ]]; then
        rm -rf "${TMP_DIR}"
    fi
}

usage() {
    cat <<'EOF'
Usage:
  ./install.sh install [--role relay|agent|all] [--force]
  ./install.sh activate [--role relay|agent|all]
  ./install.sh precheck [--role relay|agent|all]
  ./install.sh status [--role relay|agent|all]
  ./install.sh uninstall [--role relay|agent|all] [--purge]
  ./install.sh readme

Actions:
  install     Install binaries, systemd units, and config templates.
  activate    Enable and start systemd services after configs are filled in.
  precheck    Check runtime dependencies such as systemd and docker.
  status      Show service status and key file locations.
  uninstall   Stop and disable services. Configs and data are kept by default.
  readme      Print the packaged README.

Options:
  --role      relay, agent, or all (default: all)
  --force     Overwrite changed config/unit files after backing them up
  --purge     With uninstall, also remove configs, state dirs, and install base
  -h, --help  Show this help text
EOF
}

require_root() {
    if [[ "$(id -u)" -ne 0 ]]; then
        die "Please run this installer as root or with sudo."
    fi
}

normalize_role() {
    case "${1:-}" in
        relay|agent|all)
            printf '%s\n' "$1"
            ;;
        *)
            return 1
            ;;
    esac
}

want_role() {
    local candidate="$1"
    [[ "${ROLE}" == "all" || "${ROLE}" == "${candidate}" ]]
}

sha256_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        die "sha256sum or shasum is required"
    fi
}

resolve_payload() {
    local marker_line

    TMP_DIR="$(mktemp -d /tmp/harbor-relay-installer.XXXXXX)"
    PAYLOAD_ROOT="${TMP_DIR}/payload"
    mkdir -p "${PAYLOAD_ROOT}"

    marker_line="$(awk '/^__PAYLOAD_BELOW__$/ { print NR + 1; exit }' "$0" || true)"
    if [[ -n "${marker_line}" ]] && tail -n +"${marker_line}" "$0" | tar -xzf - -C "${PAYLOAD_ROOT}" >/dev/null 2>&1; then
        :
    elif [[ -f "${SCRIPT_DIR}/harbor-relay" && -f "${SCRIPT_DIR}/harbor-relay-agent" ]]; then
        cp "${SCRIPT_DIR}/harbor-relay" "${PAYLOAD_ROOT}/harbor-relay"
        cp "${SCRIPT_DIR}/harbor-relay-agent" "${PAYLOAD_ROOT}/harbor-relay-agent"
        [[ -f "${SCRIPT_DIR}/README.md" ]] && cp "${SCRIPT_DIR}/README.md" "${PAYLOAD_ROOT}/README.md"
        if [[ -d "${SCRIPT_DIR}/configs" ]]; then
            mkdir -p "${PAYLOAD_ROOT}/configs"
            cp "${SCRIPT_DIR}/configs/"*.example "${PAYLOAD_ROOT}/configs/" 2>/dev/null || true
        fi
        if [[ -d "${SCRIPT_DIR}/deploy/systemd" ]]; then
            mkdir -p "${PAYLOAD_ROOT}/deploy/systemd"
            cp "${SCRIPT_DIR}/deploy/systemd/"*.service "${PAYLOAD_ROOT}/deploy/systemd/" 2>/dev/null || true
        fi
    else
        die "No packaged payload found. Please use the .run artifact generated by build.sh/build.ps1."
    fi

    PAYLOAD_README="${PAYLOAD_ROOT}/README.md"
    PAYLOAD_MANIFEST="${PAYLOAD_ROOT}/manifest.txt"
    PAYLOAD_RELAY_BIN="${PAYLOAD_ROOT}/harbor-relay"
    PAYLOAD_AGENT_BIN="${PAYLOAD_ROOT}/harbor-relay-agent"
    PAYLOAD_RELAY_CONFIG="${PAYLOAD_ROOT}/configs/relay.yaml.example"
    PAYLOAD_AGENT_CONFIG="${PAYLOAD_ROOT}/configs/agent.yaml.example"
    PAYLOAD_RELAY_SERVICE="${PAYLOAD_ROOT}/deploy/systemd/harbor-relay.service"
    PAYLOAD_AGENT_SERVICE="${PAYLOAD_ROOT}/deploy/systemd/harbor-relay-agent.service"

    [[ -f "${PAYLOAD_RELAY_BIN}" ]] || die "payload is missing harbor-relay"
    [[ -f "${PAYLOAD_AGENT_BIN}" ]] || die "payload is missing harbor-relay-agent"
    [[ -f "${PAYLOAD_RELAY_CONFIG}" ]] || die "payload is missing relay.yaml.example"
    [[ -f "${PAYLOAD_AGENT_CONFIG}" ]] || die "payload is missing agent.yaml.example"
    [[ -f "${PAYLOAD_RELAY_SERVICE}" ]] || die "payload is missing harbor-relay.service"
    [[ -f "${PAYLOAD_AGENT_SERVICE}" ]] || die "payload is missing harbor-relay-agent.service"
}

safe_install_file() {
    local src="$1"
    local dst="$2"
    local mode="$3"
    local owner_group="$4"
    local backup_name=""

    install -d -m 0755 "$(dirname "${dst}")"

    if [[ -f "${dst}" ]] && cmp -s "${src}" "${dst}"; then
        return 0
    fi

    if [[ -f "${dst}" && "${FORCE}" -eq 0 ]]; then
        cp "${src}" "${dst}.dist"
        chmod "${mode}" "${dst}.dist"
        chown "${owner_group}" "${dst}.dist"
        warn "Detected local changes in ${dst}; wrote ${dst}.dist for manual merge."
        return 0
    fi

    if [[ -f "${dst}" && "${FORCE}" -eq 1 ]]; then
        backup_name="${dst}.bak.$(date +%Y%m%d%H%M%S)"
        cp -a "${dst}" "${backup_name}"
        log "Backed up ${dst} -> ${backup_name}"
    fi

    install -m "${mode}" "${src}" "${dst}"
    chown "${owner_group}" "${dst}"
}

prepare_directories() {
    install -d -m 0755 "${INSTALL_BASE}" "${RELEASES_DIR}" "${BIN_DIR}"
    install -d -m 0755 "${CONFIG_DIR}" "${EXAMPLES_DIR}"
    install -d -m 0755 "${RELAY_WORKDIR}" "${AGENT_WORKDIR}"
    install -d -m 0700 "${AGENT_DOCKER_CONFIG_DIR}"
}

install_binaries() {
    local release_id release_dir

    release_id="$(sha256_file "${PAYLOAD_RELAY_BIN}")-$(sha256_file "${PAYLOAD_AGENT_BIN}")"
    release_dir="${RELEASES_DIR}/${release_id}"
    install -d -m 0755 "${release_dir}"

    install -m 0755 "${PAYLOAD_RELAY_BIN}" "${release_dir}/harbor-relay"
    install -m 0755 "${PAYLOAD_AGENT_BIN}" "${release_dir}/harbor-relay-agent"

    ln -sfn "${release_dir}/harbor-relay" "${RELAY_BIN_LINK}"
    ln -sfn "${release_dir}/harbor-relay-agent" "${AGENT_BIN_LINK}"
}

install_documentation() {
    [[ -f "${PAYLOAD_README}" ]] && install -m 0644 "${PAYLOAD_README}" "${README_TARGET}"
    [[ -f "${PAYLOAD_MANIFEST}" ]] && install -m 0644 "${PAYLOAD_MANIFEST}" "${MANIFEST_TARGET}"
}

install_templates() {
    safe_install_file "${PAYLOAD_RELAY_CONFIG}" "${EXAMPLES_DIR}/relay.yaml.example" 0644 root:root
    safe_install_file "${PAYLOAD_AGENT_CONFIG}" "${EXAMPLES_DIR}/agent.yaml.example" 0644 root:root
}

install_runtime_configs() {
    if want_role "relay"; then
        safe_install_file "${PAYLOAD_RELAY_CONFIG}" "${RELAY_CONFIG}" 0644 root:root
    fi
    if want_role "agent"; then
        safe_install_file "${PAYLOAD_AGENT_CONFIG}" "${AGENT_CONFIG}" 0644 root:root
    fi
}

install_systemd_units() {
    if want_role "relay"; then
        safe_install_file "${PAYLOAD_RELAY_SERVICE}" "${RELAY_SERVICE_FILE}" 0644 root:root
    fi
    if want_role "agent"; then
        safe_install_file "${PAYLOAD_AGENT_SERVICE}" "${AGENT_SERVICE_FILE}" 0644 root:root
    fi
    if command -v systemctl >/dev/null 2>&1; then
        systemctl daemon-reload >/dev/null 2>&1 || warn "systemctl daemon-reload failed in the current environment; activate on a real systemd host later."
    fi
}

config_has_placeholders() {
    local file="$1"
    [[ -f "${file}" ]] || return 0
    if grep -Ev '^[[:space:]]*#|^[[:space:]]*$' "${file}" | grep -Eiq 'replace-with-|example\.com|changeme|<[^>]+>'; then
        return 0
    fi
    return 1
}

show_config_guidance() {
    if want_role "relay"; then
        log "Edit relay config: ${RELAY_CONFIG}"
    fi
    if want_role "agent"; then
        log "Edit agent config: ${AGENT_CONFIG}"
    fi
    log "After editing configs, run: ${PROGRAM_NAME} activate --role ${ROLE}"
}

service_status_block() {
    local service="$1"
    if systemctl list-unit-files "${service}.service" >/dev/null 2>&1; then
        systemctl --no-pager --full status "${service}" || true
    else
        warn "systemd unit not installed: ${service}.service"
    fi
}

ensure_config_ready() {
    local config_file="$1"
    local label="$2"

    [[ -f "${config_file}" ]] || die "Missing ${label} config: ${config_file}"
    if config_has_placeholders "${config_file}"; then
        die "${label} config still contains placeholders. Edit ${config_file} before activate."
    fi
}

activate_service() {
    local service_name="$1"
    if systemctl is-enabled "${service_name}" >/dev/null 2>&1; then
        systemctl restart "${service_name}"
    else
        systemctl enable --now "${service_name}"
    fi
}

precheck_action() {
    resolve_payload

    command -v systemctl >/dev/null 2>&1 || die "systemctl is required"
    if want_role "agent"; then
        command -v docker >/dev/null 2>&1 || warn "docker was not found in PATH; the agent service will fail until Docker is installed."
    fi
    "${PAYLOAD_RELAY_BIN}" --help >/dev/null 2>&1 || die "Packaged harbor-relay binary is not executable on this host"
    "${PAYLOAD_AGENT_BIN}" --help >/dev/null 2>&1 || die "Packaged harbor-relay-agent binary is not executable on this host"

    log "Precheck passed."
    log "Relay binary: ${PAYLOAD_RELAY_BIN}"
    log "Agent binary: ${PAYLOAD_AGENT_BIN}"
}

install_action() {
    require_root
    resolve_payload
    prepare_directories
    install_binaries
    install_documentation
    install_templates
    install_runtime_configs
    install_systemd_units

    log "Install completed."
    show_config_guidance
}

activate_action() {
    require_root

    if want_role "relay"; then
        ensure_config_ready "${RELAY_CONFIG}" "relay"
    fi
    if want_role "agent"; then
        ensure_config_ready "${AGENT_CONFIG}" "agent"
    fi

    systemctl daemon-reload
    if want_role "relay"; then
        activate_service "${RELAY_SERVICE_NAME}"
    fi
    if want_role "agent"; then
        activate_service "${AGENT_SERVICE_NAME}"
    fi

    log "Activation completed."
    status_action
}

status_action() {
    if want_role "relay"; then
        service_status_block "${RELAY_SERVICE_NAME}"
        echo
        log "Relay config: ${RELAY_CONFIG}"
        log "Relay state:  ${RELAY_WORKDIR}"
        if config_has_placeholders "${RELAY_CONFIG}"; then
            warn "Relay config still contains placeholders."
        fi
        echo
    fi

    if want_role "agent"; then
        service_status_block "${AGENT_SERVICE_NAME}"
        echo
        log "Agent config:        ${AGENT_CONFIG}"
        log "Agent state:         ${AGENT_WORKDIR}"
        log "Agent docker config: ${AGENT_DOCKER_CONFIG_DIR}"
        if config_has_placeholders "${AGENT_CONFIG}"; then
            warn "Agent config still contains placeholders."
        fi
        echo
    fi

    if [[ -f "${MANIFEST_TARGET}" ]]; then
        log "Installed manifest:"
        cat "${MANIFEST_TARGET}"
    fi
}

uninstall_action() {
    require_root

    if want_role "relay"; then
        systemctl disable --now "${RELAY_SERVICE_NAME}" >/dev/null 2>&1 || true
        rm -f "${RELAY_SERVICE_FILE}" "${RELAY_BIN_LINK}"
    fi
    if want_role "agent"; then
        systemctl disable --now "${AGENT_SERVICE_NAME}" >/dev/null 2>&1 || true
        rm -f "${AGENT_SERVICE_FILE}" "${AGENT_BIN_LINK}"
    fi
    systemctl daemon-reload
    systemctl reset-failed >/dev/null 2>&1 || true

    if [[ "${PURGE}" -eq 1 ]]; then
        if [[ "${ROLE}" == "all" || "${ROLE}" == "relay" ]]; then
            rm -rf "${RELAY_WORKDIR}"
        fi
        if [[ "${ROLE}" == "all" || "${ROLE}" == "agent" ]]; then
            rm -rf "${AGENT_WORKDIR}"
        fi
        if [[ "${ROLE}" == "all" ]]; then
            rm -rf "${CONFIG_DIR}" "${INSTALL_BASE}"
        fi
    fi

    log "Uninstall completed."
    if [[ "${PURGE}" -eq 0 ]]; then
        warn "Configs and state directories were kept. Re-run with --purge to remove them."
    fi
}

readme_action() {
    resolve_payload
    if [[ -f "${PAYLOAD_README}" ]]; then
        cat "${PAYLOAD_README}"
    elif [[ -f "${README_TARGET}" ]]; then
        cat "${README_TARGET}"
    else
        usage
    fi
}

parse_args() {
    if [[ $# -gt 0 ]]; then
        case "$1" in
            install|activate|precheck|status|uninstall|readme)
                ACTION="$1"
                shift
                ;;
        esac
    fi

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --role)
                ROLE="$(normalize_role "${2:-}")" || die "Unsupported role: ${2:-}"
                shift 2
                ;;
            --force)
                FORCE=1
                shift
                ;;
            --purge)
                PURGE=1
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                die "Unknown argument: $1"
                ;;
        esac
    done
}

main() {
    trap cleanup EXIT
    parse_args "$@"

    case "${ACTION}" in
        install)
            install_action
            ;;
        activate)
            activate_action
            ;;
        precheck)
            precheck_action
            ;;
        status)
            status_action
            ;;
        uninstall)
            uninstall_action
            ;;
        readme)
            readme_action
            ;;
        *)
            die "Unsupported action: ${ACTION}"
            ;;
    esac
}

main "$@"
exit 0

__PAYLOAD_BELOW__
